service: react-serverless-practice

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'ap-northeast-2'}
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-s3-sync
  - serverless-stack-termination-protection

custom:
  serverlessTerminationProtection:
    stages:
      - prod
  bucketName: aws-serverless-practice-react-app
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: build
      params:
        - index.html:
            CacheControl: "no-cache, max-age=30"
        - outdated-browser.html:
            CacheControl: "no-cache, max-age=30"
        - "**/*.js":
            CacheControl: "public, max-age=31536000"
        - "**/*.css":
            CacheControl: "public, max-age=31536000"
        - "static/media/*":
            CacheControl: "public, max-age=31536000"

resources:
  Resources:
    WebAppCloudFrontOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: ${self:service}-${self:provider.stage}

    WebAppBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    WebAppBucketPolicy:
      Type: AWS::S3::BucketPolicy
      DependsOn:
        - WebAppCloudFrontOriginAccessIdentity
      Properties:
        Bucket:
          Ref: WebAppBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - Ref: WebAppBucket
                    - "/*"

    WebAppCloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      DependsOn: WebAppBucketPolicy
      Properties:
        DistributionConfig:
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            TargetOriginId: ${self:service}
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          DefaultRootObject: index.html
          Enabled: true
          HttpVersion: http2
          Logging:
            IncludeCookies: false
            Bucket: ${self:custom.bucketName}.s3.amazonaws.com
            Prefix: cf-logs
          Origins:
            - DomainName: ${self:custom.bucketName}.s3.amazonaws.com
              Id: ${self:service}
              S3OriginConfig:
                OriginAccessIdentity:
                  Fn::Join:
                    - ""
                    - - "origin-access-identity/cloudfront/"
                      - Ref: WebAppCloudFrontOriginAccessIdentity

  Outputs:
    WebAppBucket:
      Value:
        Ref: WebAppBucket
    WebAppCloudFrontDistributionDomainName:
      Value:
        Fn::GetAtt: [WebAppCloudFrontDistribution, DomainName]